In [ ]:
import numpy as np
a=np.array([3,1,2])
b=np.array([0,3,4])
c=a+b
print(c)

[3 4 6]


In [ ]:
import numpy as np
a=np.array([3,1,2])
b=np.array([0,3,4])
c=a-b
print(c)

[ 3 -2 -2]


In [ ]:
import numpy as np
a=np.array([3,1,2])
b=np.array([0,3,4])
c=a*b
print(c)

[0 3 8]


In [ ]:
import numpy as np
a=np.array([3,1,2])
b=np.array([1,1,4])
c=a/b
print(c)

[3.  1.  0.5]


In [ ]:
import numpy as np
a=np.array([4,3,4])
mean_a=np.mean(a)
print(mean_a)

3.6666666666666665


In [ ]:
import numpy as np
a=np.array([4,3,4])
median_a=np.median(a)
print(median_a)

4.0


In [ ]:
import numpy as np
a=np.array([4,3,4])
std_a=np.std(a)
print(std_a)

0.4714045207910317


In [ ]:
import numpy as np
a=np.array([0b1010,0b1100,0b0100])
b=np.array([0b1111,0b0000,0b1001])
c=np.bitwise_or(a,b)
print(c)

[15 12 13]


In [ ]:
import numpy as np
a=np.array([0b1010,0b1100,0b0100])
b=np.array([0b1111,0b0000,0b1001])
c=np.bitwise_and(a,b)
print(c)

[10  0  0]


In [ ]:
import numpy as np
a=np.array([0b1010,0b1100,0b0100])
c=np.bitwise_not(a,b)
print(c)

[-11 -13  -5]


In [ ]:
import numpy as np
b=np.array([0b1111,0b0000,0b1001])
c=np.bitwise_not(a,b)
print(c)

[-11 -13  -5]


In [ ]:
arr1=np.array([1,2,3])
arr2=arr1.copy()
arr2[0]


1

In [ ]:
arr1=np.array([1,2,3])
arr2=arr1.copy()
arr2[0]=4
print(arr1)
print(arr2)


[1 2 3]
[4 2 3]


In [ ]:
arr1=np.array([1,2,3])
arr2=arr1.view()
arr2[0]=4
print(arr1)
print(arr2)


[4 2 3]
[4 2 3]


In [ ]:
arr1=np.array([1,2,3])
arr2=np.array([3,2,1])
arr3=np.hstack((arr1,arr2))
print(arr3)



[1 2 3 3 2 1]


In [ ]:
print(*range(1,101))

1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 100


In [ ]:
x = range(3, 33, 3)

for n in x:
  print(n)
x =(range(4, 44, 4))

for n in x:
  print(n)
